import type { RouteType, RouteStyle } from '../types'

export const COMPANY_ROUTE_STYLES: Record<
  string,
  Partial<Record<RouteType, RouteStyle>>
> = {
  kmb: {
    regular: {},
    xhtEhc: { backgroundColor: '#CF0001', color: '#ffffff' },
    marathon: { backgroundColor: '#CF0001', color: '#ffffff' },
    whc: { backgroundColor: '#027233', color: '#ffffff' },
    airport: { backgroundColor: '#0A2163', color: '#FFFF00' },
    external: { backgroundColor: '#ff5000', color: '#ffffff' },
    overnight: { backgroundColor: '#000000', color: '#ffffff' },
    airportOvernight: { backgroundColor: '#000000', color: '#FFFF00' },
    premier: { backgroundColor: '#E5B034', color: '#ffffff' },
    shuttle: { backgroundColor: '#EB5136', color: '#0E2775' },
    disneyRecreational: { backgroundColor: '#146FD1', color: '#ffffff'  },
    r8: { backgroundColor: '#72C8E5', color: '#1C2EB5' },
    awe: { backgroundColor: '#6F2F9F', color: '#ffffff' },
  },
  ctb: {
    regular: { backgroundColor: '#0059BD', color: '#ffffff' },
    xhtEhc: { backgroundColor: '#CF0001', color: '#ffffff' },
    whc: { backgroundColor: '#027233', color: '#ffffff' },
    airport: { backgroundColor: '#BB2B44', color: '#ffffff' },
    external: { backgroundColor: '#DB3831', color: '#FFFFFF' },
    overnight: { backgroundColor: '#000000', color: '#FFFF00' },
    airportOvernight: { backgroundColor: '#CF314B', color: '#ffffff' },
    disneyRecreational: { backgroundColor: '#72C8E5', color: '#1C2EB5' },
    r8: { backgroundColor: '#72C8E5', color: '#1C2EB5' },
    shuttle: { backgroundColor: '#0E2775', color: '#ffffff' },
    peak: { backgroundColor: '#3CC3D9', color: '#ffffff' },
    hkSightseeing: { backgroundColor: '#679AD1', color: '#ffffff' },
    marathon: { backgroundColor: '#CF0001', color: '#ffffff' },
  },
  nlb: {
    regular: { backgroundColor: '#000080', color: '#ffffff' },
    airport: { backgroundColor: '#DB3831', color: '#FFFF00' },
    overnight: { backgroundColor: '#000000', color: '#FFFF00' },
    nlbSpecial: { backgroundColor: '#027233', color: '#ffffff' },
    nlbExpress: { backgroundColor: '#000080', color: '#FFFF00' },
  },
  mtr: {
    mtrTkl: { backgroundColor: '#7F3D91', color: '#ffffff' },
    mtrTwl: { backgroundColor: '#FF0000', color: '#ffffff' },
    mtrKtl: { backgroundColor: '#007500', color: '#ffffff' },
    mtrSil: { backgroundColor: '#CFCF0A', color: '#ffffff' },
    mtrTml: { backgroundColor: '#992E05', color: '#ffffff' },
    mtrAel: { backgroundColor: '#087D86', color: '#ffffff' },
    mtrIsl: { backgroundColor: '#0175BB', color: '#ffffff' },
    mtrEal: { backgroundColor: '#5BB7E9', color: '#ffffff' },
    mtrDrl: { backgroundColor: '#E86CA4', color: '#ffffff' },
    mtrTcl: { backgroundColor: '#E3A147', color: '#ffffff' },
  },
}

type RouteTypeRule = { type: RouteType; regex: RegExp }

export const COMPANY_ROUTE_TYPE_RULES: Record<string, RouteTypeRule[]> = {
  kmb: [
    { type: 'regular', regex: /^(331)[S]?/ },
    { type: 'xhtEhc', regex: /^[136]\d{2}[A-Z]?$/ },
    { type: 'whc', regex: /^9(?!17|18|45$)\d{2}[A-Z]?$/ },
    { type: 'overnight', regex: /^(N(?!A)[A-Z0-9]+|270S|271S|293S)$/i },
    { type: 'airport', regex: /^A/ },
    { type: 'airportOvernight', regex: /^NA/ },
    { type: 'external', regex: /^E/ },
    { type: 'shuttle', regex: /^S(?!P)/ },
    { type: 'premier', regex: /^P96[08]$/ },
    { type: 'disneyRecreational', regex: /^R(33|42)$/i },
    { type: 'r8', regex: /^R8$/i },
    { type: 'marathon', regex: /^R(108|307|603|673|678|680|934|936|948|960|961|968)$/i },
    { type: 'awe', regex: /^X(33|36|40|43|47)$/i },
  ],
  ctb: [
    { type: 'airportOvernight', regex: /^NA/ },
    { type: 'airport', regex: /^A/ },
    { type: 'xhtEhc', regex: /^(?!629[A-Z]?$)[136]\d{2}[A-Z]?$/ },
    { type: 'whc', regex: /^X?9\d{2}[A-Za-z]?$/ },
    { type: 'external', regex: /^[BE]/ },
    { type: 'overnight', regex: /^N/i },
    { type: 'disneyRecreational', regex: /^R(11|22)$/i },
    { type: 'r8', regex: /^R8$/i },
    { type: 'peak', regex: /^X?15[B]?$/i },
    { type: 'shuttle', regex: /^S(?!P)/i },
    { type: 'hkSightseeing', regex: /^H/i },
    { type: 'marathon', regex: /^R(307|680|796|930|948|950|962|969)$/i},
  ],
  nlb: [
    { type: 'airport', regex: /^A/ },
    { type: 'overnight', regex: /^N/i },
    { type: 'nlbSpecial', regex: /^(7|34)S$/i },
    { type: 'nlbExpress', regex: /^(X11R|XB2|NB2)$/i },
  ],
  mtr: [
    { type: 'mtrTkl', regex: /^TKL$/i },
    { type: 'mtrTwl', regex: /^TWL$/i },
    { type: 'mtrKtl', regex: /^KTL$/i },
    { type: 'mtrSil', regex: /^SIL$/i },
    { type: 'mtrTml', regex: /^TML$/i },
    { type: 'mtrAel', regex: /^AEL$/i },
    { type: 'mtrIsl', regex: /^ISL$/i },
    { type: 'mtrEal', regex: /^EAL$/i },
    { type: 'mtrDrl', regex: /^DRL$/i },
    { type: 'mtrTcl', regex: /^TCL$/i },
  ],
  default: [],
}
